name: TelephoneGameSpigot
version: '1.0-SNAPSHOT'
main: me.elec.telephoneGameSpigot.TelephoneGameSpigot
api-version: '1.21'
depend: [voicechat]
commands:
  call:
    description: Call another user.
    usage: call [player]
  bribe:
    description: Used to bribe another user.
    usage: bribe [player]
  startgame:
    description: Starts the telephone game.
    usage: startgame